---
title: "DateCreekCruise"
author: "Myarham"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(ggplot2)
library(tidyverse)
library(data.table)
require(readxl)
```

Import Raw Data

```{r import raw data and clean}
cruise.data1 <- read_xlsx("F:/OneDrive - Government of BC/MixedStands/KispioxCruise_bytree_FINAL.xlsx")
cruise.data <- read_xlsx("F:/OneDrive - Government of BC/MixedStands/KispioxCruise_bytree_FINAL.xlsx", sheet = "Compilation volumes") %>%         select(Licence, BlockID, treatment, rep)  %>% left_join(cruise.data1)
cruise.data$Species <- cruise.data$Species %>%
    str_replace_all(c("S" = "Sx", "H" = "Hw", "PL" = "Pl", "C" = "Cw", "AT" = "At", "AC" = "Ac", "B" = "Bl", "E" = "Ep"))
plot.numbering <- cruise.data %>% select(BlockID, Plot) %>% distinct () %>% group_by(BlockID) %>% mutate(plot_no = row_number()) %>% filter(!is.na(BlockID)) %>% distinct()

 tree.data <- cruise.data %>% left_join(plot.numbering, by=c("BlockID", "Plot"))%>% select(Licence, BlockID, treatment, rep, plot_no,Tree,Species, HT, DBH, Stems_ha, Gross_Bio, TC) %>%
   filter(complete.cases(.))
fwrite(tree.data, "./clean_data/cleaned_treedata.csv")
si.data <- cruise.data %>% select(Licence, BlockID, treatment, rep, Plot, Tree, Species, HT, CountedAge, SiteIndex, AgeCorrection, CorrectedAge) %>% 
   filter(!is.na(CountedAge))
fwrite(si.data, "./clean_data/cleaned_SI50data.csv")
cruise.info <- read_xlsx("F:/OneDrive - Government of BC/MixedStands/KispioxCruise_bytree_FINAL.xlsx", sheet = "Compilation volumes") %>%         select(Licence, BlockID, treatment)
doth.data <- read_xlsx("F:/OneDrive - Government of BC/MixedStands/KispioxCruise_bytree_FINAL.xlsx", sheet = "Dothistroma") %>% left_join(cruise.info) %>% left_join(tree.data, by=c("Licence", "Plot", "Tree")) %>% select(Licence, BlockID.x, treatment.x, rep, Plot, Species, Tree, HT, DBH, Gross_Bio, LiveCrown, Healthy) %>% rename(BlockID = BlockID.x, treatment = treatment.x)
fwrite(doth.data, "./clean_data/cleaned_doth_data.csv")

```


Import Clean data
```{r trees by block by plot}
datecreekcruise <- fread("./clean_data/cleaned_treedata.csv")

# Block <- c(rep("413", 8), rep("440", 8), rep("472", 8), rep("473", 8), rep("528", 8), rep("657", 8), rep("676", 8), rep("677", 8), rep("715", 8), rep("738", 8), rep("795", 8), rep("818", 8))
# Species <- rep(c("Sx", "Pl", "Hw", "Cw", "Ep", "Bl", "At"), 4)
# Stems_ha <- c(0,100,200,300,400,500,600,700,800,900,1000,1100,1200)
remove.tree <- c(125, 109)#
###remove identified mature trees
data <- datecreekcruise %>% rowid_to_column("tree_no") %>% filter(!tree_no %in% remove.tree)
xx <- data %>% filter(Species == "At")

ggplot(data, aes(x = plot_no, y = Gross_Bio, fill = Species)) +
  geom_col(colour = "black", position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_brewer(palette = "Pastel1")+
  facet_wrap(~treatment+rep)

ggplot(data, aes(x=plot_no, y=Gross_Bio, fill=Species)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(title = "Stems per Hectare by Block and Species",
       x = "Block",
       y = "Stems per Hectare",
       fill = "Species") +
  theme_minimal()+
    facet_wrap(~treatment+rep)
```

